<?php
namespace Database\Seeders;
use App\Models\InvitationTemplate;
use Illuminate\Database\Seeder;

class TemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            ['name'=>'Elegant Gold','slug'=>'elegant-gold','description'=>'Template elegan dengan aksen emas yang mewah','category'=>'elegant','color_primary'=>'#D4AF37','color_secondary'=>'#1a1a2e','color_accent'=>'#f8f0e3','font_heading'=>'Playfair Display','font_body'=>'Lato','blade_view'=>'templates.elegant-gold','is_premium'=>false,'is_active'=>true,'sort_order'=>1],
            ['name'=>'Minimal White','slug'=>'minimal-white','description'=>'Desain minimalis bersih dengan nuansa putih modern','category'=>'minimal','color_primary'=>'#2d2d2d','color_secondary'=>'#ffffff','color_accent'=>'#f5f5f5','font_heading'=>'Cormorant Garamond','font_body'=>'Montserrat','blade_view'=>'templates.minimal-white','is_premium'=>false,'is_active'=>true,'sort_order'=>2],
            ['name'=>'Luxury Black','slug'=>'luxury-black','description'=>'Template mewah dengan tema gelap dan aksen emas','category'=>'luxury','color_primary'=>'#C9A96E','color_secondary'=>'#0d0d0d','color_accent'=>'#1a1a1a','font_heading'=>'Cinzel','font_body'=>'Raleway','blade_view'=>'templates.luxury-black','is_premium'=>true,'is_active'=>true,'sort_order'=>3],
            ['name'=>'Floral Romantic','slug'=>'floral-romantic','description'=>'Template romantis dengan ornamen bunga','category'=>'floral','color_primary'=>'#8B4513','color_secondary'=>'#FFF8F0','color_accent'=>'#FFE4E1','font_heading'=>'Great Vibes','font_body'=>'Open Sans','blade_view'=>'templates.floral-romantic','is_premium'=>true,'is_active'=>true,'sort_order'=>4],
            ['name'=>'Islamic Elegant','slug'=>'islamic-elegant','description'=>'Template Islami elegan dengan ornamen geometris','category'=>'islamic','color_primary'=>'#1B5E20','color_secondary'=>'#F5F5DC','color_accent'=>'#E8F5E9','font_heading'=>'Amiri','font_body'=>'Poppins','blade_view'=>'templates.islamic-elegant','is_premium'=>true,'is_active'=>true,'sort_order'=>5],
            ['name'=>'Modern Geometric','slug'=>'modern-geometric','description'=>'Template modern dengan elemen geometris dan animasi elegan','category'=>'modern','color_primary'=>'#1a1a2e','color_secondary'=>'#f8f6f4','color_accent'=>'#c9a87c','font_heading'=>'Italiana','font_body'=>'Josefin Sans','blade_view'=>'templates.modern-geometric','is_premium'=>true,'is_active'=>true,'sort_order'=>6],
            ['name'=>'Romantic Blush','slug'=>'romantic-blush','description'=>'Template romantis dengan warna blush pink yang lembut','category'=>'romantic','color_primary'=>'#D4A5A5','color_secondary'=>'#3D3D3D','color_accent'=>'#F5E6E0','font_heading'=>'Cormorant Garamond','font_body'=>'Montserrat','blade_view'=>'templates.romantic-blush','is_premium'=>false,'is_active'=>true,'sort_order'=>7],
            ['name'=>'Art Watercolor','slug'=>'art-watercolor','description'=>'Template artistik dengan nuansa watercolor dan ornamen cat air yang elegan','category'=>'art','color_primary'=>'#7B8E6B','color_secondary'=>'#3D3D3D','color_accent'=>'#F5EFE6','font_heading'=>'Cormorant Garamond','font_body'=>'Josefin Sans','blade_view'=>'templates.art-watercolor','is_premium'=>true,'is_active'=>true,'sort_order'=>8],
            ['name'=>'Art 05 - Prewed Cover','slug'=>'art-05','description'=>'Template artistik dengan halaman buka undangan full screen foto prewed sebagai background','category'=>'art','color_primary'=>'#D4A574','color_secondary'=>'#2C2C2C','color_accent'=>'#F8F5F0','font_heading'=>'Cormorant Garamond','font_body'=>'Montserrat','blade_view'=>'templates.art-05','is_premium'=>true,'is_active'=>true,'sort_order'=>9],
            ['name'=>'Cream Purple','slug'=>'cream-purple','description'=>'Template elegan bernuansa krem dan ungu lembut dengan ornamen bunga','category'=>'elegant','color_primary'=>'#9F709A','color_secondary'=>'#ded7c7','color_accent'=>'#f5f0e8','font_heading'=>'Playfair Display','font_body'=>'Marcellus','blade_view'=>'templates.cream-purple','is_premium'=>false,'is_active'=>true,'sort_order'=>10],
            ['name'=>'Indonesia Classic','slug'=>'indonesia-classic','description'=>'Template klasik Indonesia dengan nuansa tradisional dan ornamen batik','category'=>'classic','color_primary'=>'#6B5B4B','color_secondary'=>'#F5F0E8','color_accent'=>'#E8DFD0','font_heading'=>'Marcellus','font_body'=>'Jost','blade_view'=>'templates.indonesia-classic','is_premium'=>true,'is_active'=>true,'sort_order'=>11],
            ['name'=>'Rustic Garden','slug'=>'rustic-garden','description'=>'Template rustic dengan nuansa taman alami dan elemen kayu','category'=>'rustic','color_primary'=>'#4A6741','color_secondary'=>'#F5F0E8','color_accent'=>'#E8E0D0','font_heading'=>'Amatic SC','font_body'=>'Josefin Sans','blade_view'=>'templates.rustic-garden','is_premium'=>true,'is_active'=>true,'sort_order'=>12],
            ['name'=>'Tropical Paradise','slug'=>'tropical-paradise','description'=>'Template tropis ceria dengan nuansa pantai dan warna-warni tropical','category'=>'tropical','color_primary'=>'#E8756D','color_secondary'=>'#2BA5A5','color_accent'=>'#FFF5E6','font_heading'=>'Pacifico','font_body'=>'Nunito','blade_view'=>'templates.tropical-paradise','is_premium'=>true,'is_active'=>true,'sort_order'=>13],
            ['name'=>'Vintage Rose','slug'=>'vintage-rose','description'=>'Template vintage dengan nuansa mawar klasik yang romantis','category'=>'vintage','color_primary'=>'#C4888B','color_secondary'=>'#A06568','color_accent'=>'#FFF5F0','font_heading'=>'EB Garamond','font_body'=>'Lora','blade_view'=>'templates.vintage-rose','is_premium'=>true,'is_active'=>true,'sort_order'=>14],
        ];
        foreach ($templates as $t) InvitationTemplate::updateOrCreate(['slug' => $t['slug']], $t);
    }
}
