services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: undangan_prod_app

    restart: unless-stopped

    ports:
      - "8021:80"

    env_file:
      - ../.env

    networks:
      - shared

networks:
  shared:
    external: true